Return items of multi-select in order of selection
skim-rs/skim pull request #468
Opened 2022-07-22 02:58 UTC by otto-dev

Fixes #464. Also preserves the order of `--pre-select-items` when returning them unchanged.

The introduced `linked-hash-map` dependency will continue to receive bug-fixes and updates to rust versions, but there are not plans to add further features to the library.

2024-11-17 22:20 UTC, yazgoo commented on Cargo.toml
> +defer-drop = "1.0.1"
why downgrading some packages

2024-11-17 22:24 UTC, yazgoo approved these changes

2024-11-17 22:25 UTC, yazgoo requested changes
see previous question

2024-11-18 16:20 UTC, LoricAndre commented on Cargo.toml
> +defer-drop = "1.0.1"
should be fixed

2024-11-18 21:07 UTC, yazgoo approved these changes
looks ok to me

2024-11-18 21:16 UTC, merged